In [3]:
!pip install numpy

In [5]:
import numpy as np

# Create Numpy array

In [6]:
a= np.array([2,3,4])

In [7]:
print(a)

[2 3 4]


In [8]:
#arange(start,end,step)
a=np.arange(2,12,2)

In [9]:
print (a)

[ 2  4  6  8 10]


In [32]:
#alinspace (st,end,no of elements)
a=np.linspace(1,10,8)

In [33]:
a

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

In [34]:
#reshape
a.reshape(4,2)

array([[ 1.        ,  2.28571429],
       [ 3.57142857,  4.85714286],
       [ 6.14285714,  7.42857143],
       [ 8.71428571, 10.        ]])

In [35]:
# a.size give the total no of elements in array
# a.shape
#a.dtype

In [36]:
#a.itemsize

In [49]:
b=np.array([(2,3,4),(2,3,4)])

In [48]:
b

2

In [42]:
b*2

array([[4, 6, 8],
       [4, 6, 8]])

In [43]:
b/2

array([[1. , 1.5, 2. ],
       [1. , 1.5, 2. ]])

In [45]:
a<2

False

In [46]:
b=2

In [50]:
b<  4

array([[ True,  True, False],
       [ True,  True, False]])

In [53]:
#random function
c= np.random.random((4,4))

In [54]:
c

array([[0.6152175 , 0.44497776, 0.68668469, 0.2567582 ],
       [0.59290153, 0.47521628, 0.16462835, 0.11345049],
       [0.97978839, 0.36658779, 0.1944913 , 0.62725823],
       [0.83619736, 0.17106732, 0.63456159, 0.06200593]])

In [55]:
#print random array but without many decimal places
np.set_printoptions(precision=2,suppress=2)

In [56]:
c

array([[0.62, 0.44, 0.69, 0.26],
       [0.59, 0.48, 0.16, 0.11],
       [0.98, 0.37, 0.19, 0.63],
       [0.84, 0.17, 0.63, 0.06]])

In [59]:
# array of randon integers
d=np.random.randint(0,10,5)

In [60]:
d

array([1, 0, 7, 5, 5])

In [61]:
#SUM of all elements of arrray
d.sum()

18

In [62]:
c.sum()

7.221792705210939

In [63]:
# MIN and MAX
d.min()
d.max()

7

In [64]:
d.min()

0

In [66]:
d.var()

7.040000000000001

In [67]:
d.std()

2.65329983228432

In [84]:
e=np.array([10,12,13,14,16,1])

In [85]:
e=e.reshape(3,2)

e.sum()

In [86]:
e

array([[10, 12],
       [13, 14],
       [16,  1]])

In [82]:
e.sum()

66

In [88]:
e.sum(axis=1)

array([22, 27, 17])

# Read CSV file

In [93]:
data=np.loadtxt("C:\\Users\\Shubhanshu\\Desktop\\DataScience\\Python- Bootcamp\\Variables\\data.txt",dtype=np.uint8,delimiter=",")

In [94]:
data

array([1, 2, 3, 4, 5, 3], dtype=uint8)

In [95]:
d1=data.reshape(2,3)

In [96]:
d1

array([[1, 2, 3],
       [4, 5, 3]], dtype=uint8)

In [ ]:
#np.random.choice()
#np.random.shuffle()